#  Numpy Basics

In [52]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list)

In [4]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [5]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
# create a even numbers up to 11
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
# tuples for 2d matrices
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones(4)

array([1., 1., 1., 1.])

In [16]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
# 10 evenly spaced points between 0 to 5
# don't confuse with arange
np.linspace(0, 5, 100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [20]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
np.random.rand(5)

array([0.58355774, 0.09437308, 0.8956805 , 0.0518076 , 0.41641819])

In [26]:
# this is for uniform distribution shift + tab to check 
# 2d arrays don't use tuples for this function
np.random.rand(5,5)

array([[0.61902522, 0.35884579, 0.77817367, 0.34890711, 0.27776528],
       [0.58770486, 0.76671083, 0.28624727, 0.49349209, 0.1419877 ],
       [0.21290423, 0.53525549, 0.14669513, 0.1635614 , 0.19479477],
       [0.06859601, 0.216629  , 0.46378522, 0.38193613, 0.35928302],
       [0.75600063, 0.01863664, 0.86594171, 0.37745772, 0.5436381 ]])

In [27]:
# or use normal distribution
np.random.randn(4,4)

array([[-0.17055636,  0.26966924,  0.2255196 , -1.38389327],
       [-0.48143175,  0.34810068, -0.58236756, -1.8198174 ],
       [ 0.78754483, -0.43592604,  0.66271849,  0.50826289],
       [-1.21367006, -1.39467206, -1.8897314 , -1.5932456 ]])

In [33]:
# back to tuples low, high, size
np.random.randint(1, 100, (2,2))

array([[93, 33],
       [51, 84]])

In [41]:
ranarr = np.random.randint(0,100,25)
ranarr

array([59, 47, 54, 39, 18, 11,  4, 36, 97, 63, 65, 62, 16, 22, 75, 73, 16,
       42, 16, 58,  7, 21, 80,  2, 93])

In [43]:
# reshape into a 2d matrix
ranarr.reshape(5,5)

array([[59, 47, 54, 39, 18],
       [11,  4, 36, 97, 63],
       [65, 62, 16, 22, 75],
       [73, 16, 42, 16, 58],
       [ 7, 21, 80,  2, 93]])

In [44]:
ranarr.max(), ranarr.min()

(97, 2)

In [45]:
ranarr.argmax(), ranarr.argmin()

(8, 23)

In [48]:
ranarr.reshape(5,5).shape

(5, 5)

In [51]:
# find out the datatype
arr.dtype

dtype('int64')

# Indexing and Selection

In [55]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
arr[8]

8

In [57]:
arr[1:5]

array([1, 2, 3, 4])

In [58]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [59]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [102]:
slice_of = arr[0:6]
# broadcasting assignment
slice_of[:5] = 100

In [69]:
# SLICING DOES NOT COPY, CREATES A VIEW TO THE ORIGINAL ARRAY
# SLICING IN PYTHON DOES NOT COPY OBJECTS AS WELL EVERYTHING IS REFERENCE TYPES
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [70]:
# USE DEEP COPY
arr_copy = arr.copy()

In [73]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [75]:
arr_2d[1][1]

25

In [76]:
# better notation 
arr_2d[1,2]

30

In [90]:
# can use slicing to get subsections
arr_2d[1:, :2]
arr_2d[2,:]

array([35, 40, 45])

In [81]:
arr = np.arange(1,11)

In [82]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [85]:
# comparison array create boolean array
bool_arra = arr > 5
bool_arra

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [87]:
arr[bool_arra]

array([ 6,  7,  8,  9, 10])

In [88]:
# we can shortcut this by using the following notation
arr[arr < 3]

array([1, 2])

# Numpy Operations

In [106]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [107]:
# most operation is similar
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [108]:
b = arr + 2
b

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [115]:
# when you divide a number by zero you get NaN
arr / arr

/Users/seanhsu/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [116]:
np.NaN # is a type

nan

In [117]:
# same with infinity
1 / arr

/Users/seanhsu/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [118]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [123]:
# also other broadcast methods
# this is also known as universal functions
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [124]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [125]:
np.log(arr)

/Users/seanhsu/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [126]:
np.max(arr), np.min(arr)

(10, 0)